version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/opt/app
      - backend_static:/static
      - backend_media:/media
      - backend_logs:/logs
    env_file:
      - ./backend/.env
    expose:
      - "8000"  # Приложение слушает на 8000 порту
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_static:/usr/share/nginx/html
    expose:
      - "80"  # Фронтенд будет слушать на порту 80
    depends_on:
      - backend
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Экспонируем порт 80 для доступа извне
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Подключаем конфигурацию Nginx
      - frontend_static:/usr/share/nginx/html  # Статика для фронтенда
    depends_on:
      - frontend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  backend_static:
  backend_media:
  backend_logs:
  frontend_static:
