version: '3'

volumes:
  static:
  media:

services:
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
  gateway:
    build: ./gateway/
    ports:
      - 8000:80
    volumes:
      - static:/stati—Åfiles/
      - media:/media/