# Generated by Django 5.1.1 on 2024-09-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_section_redbookentry_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
    ]
