# Generated by Django 5.1.1 on 2024-09-18 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_observation_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redbookentry',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.section', verbose_name='раздел'),
        ),
    ]
