# Generated by Django 5.1.1 on 2024-09-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_redbookentry_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='approval_personal_data',
            field=models.BooleanField(default=False, verbose_name='согласие на обработку персональных данных'),
        ),
    ]
